services:
  frontend:
    container_name: ownlogs-docs
    image: ownlogs/docs:latest
    environment:
      ORIGIN: http://localhost:8184
      HOST: 0.0.0.0
      PORT: 3000
    ports:
      - '8184:3000'
